package app.justthecarbs.ocr

import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The eighteenth session's three separatorless pairs, replayed through the real recovery rules.
 *
 * ## What these captures recorded
 *
 * `docs/Scan Evıdence 4th test`, a Samsung SM-S928B. Three captures whose carbohydrate row printed
 * two values and kept a decimal separator on neither, so [ScaleAmbiguity] demonstrated a common
 * rescaling of the pair — and the recovery list then refused one member and offered the other:
 *
 * | capture | recognised row | suppressed | offered |
 * |---|---|---|---|
 * | `160639-565` | `Koolhydraten/Glucides 46 g 12 g` | `46` | **`12` -> 12 g / serving** |
 * | `160501-961` | `koolhydraten, waarvan 159 18` | `159` | **`18` -> 18 g / serving** |
 * | `160532-812` | `koolhydraten, waarvan 15 g 38g` | `15` | **`38g` -> 38 g / 25 g** |
 *
 * The offered member reached the screen because it was the **rightmost** cell, and
 * [ScaleAmbiguity] searched for a paired value only to the candidate's right — so the last column on
 * a row could never see the pair that had just refused its neighbour. See [ScalePairSymmetryTest]
 * for the unit-level statement of the rule; this file asserts the consequence at the surface the user
 * actually touches.
 *
 * ## Why a refusal here is the right outcome and not a lost reading
 *
 * A withheld figure is not a discarded one. Each of these routes to focused entry with the frozen
 * photograph, the highlighted row and the basis the label stated all preserved; the user reads the
 * digits off the package in their hand and types them. What is withdrawn is the app's permission to
 * *propose* digits whose decimal scale its own evidence says it cannot determine.
 *
 * Nothing here repairs a value. `46` never becomes `4.6` and `12` never becomes `1.2`.
 *
 * ## The fixtures
 *
 * [EighteenthSessionPairFixtures] is generated by `tools/derive-session-fixtures.py` from each
 * bundle's own `diagnostics.txt`, and the tool asserts the parsed element count against the count
 * the device declared (160, 179 and 167). The geometry is the phone's; no box here was invented or
 * adjusted to make a test pass.
 */
class EighteenthSessionPairRegressionTest {

    /**
     * The row's own text, so a failure says which capture and which row it is about.
     *
     * Asserted as a precondition in every case below: if a future change to row reconstruction moved
     * the carbohydrate declaration, these tests would otherwise pass vacuously by finding no
     * candidates at all — which is the exact shape of a green test measuring nothing.
     */
    private fun carbohydrateRowText(document: OcrDocument): String? =
        NutritionDocumentModel.build(document).panels
            .flatMap { it.declarations }
            .firstOrNull { it.kind == NutritionRowKind.TOTAL_CARBOHYDRATE }
            ?.sourceRows
            ?.joinToString(" ") { row -> row.elements.joinToString(" ") { it.text } }

    private fun offeredAmounts(document: OcrDocument): List<String> =
        RecoveryCandidates.of(document).map { it.reading.amount.stripTrailingZeros().toPlainString() }

    /**
     * `160639-565` — the capture the defect was found on.
     *
     * `46` was already suppressed. `12` is the same pair seen from the other side and must be too.
     */
    @Test
    fun `neither member of the protein bar's separatorless pair is offered`() {
        val document = EighteenthSessionPairFixtures.proteinBar160639()

        val row = carbohydrateRowText(document)
        assertNotNull("precondition: the carbohydrate declaration must still be found", row)
        assertTrue(
            "precondition: the row must still carry both members of the pair, was '$row'",
            row!!.contains("46") && row.contains("12"),
        )

        val offered = offeredAmounts(document)
        assertTrue(
            "'12' is refused by the same evidence that refused '46'; the bundle offered " +
                "'12 g / serving', was $offered",
            offered.none { it == "12" },
        )
        assertTrue(
            "'46' must stay suppressed — this is the control, was $offered",
            offered.none { it == "46" },
        )
    }

    /** `160501-961` — `159` suppressed, `18` offered. Same shape, different package. */
    @Test
    fun `neither member of the 159-18 pair is offered`() {
        val document = EighteenthSessionPairFixtures.crispsServing160501()

        val row = carbohydrateRowText(document)
        assertNotNull("precondition: the carbohydrate declaration must still be found", row)

        val offered = offeredAmounts(document)
        assertTrue("the bundle offered '18 g / serving', was $offered", offered.none { it == "18" })
        assertTrue("'159' must stay suppressed, was $offered", offered.none { it == "159" })
    }

    /**
     * `160532-812` — `15` suppressed, `38g` offered under a [app.justthecarbs.domain.CarbBasis]
     * carrying a declared `25 g` quantity.
     *
     * The declared serving is what admitted it past [ReadingEligibility]: a serving sentence the
     * label printed is normally its own scale evidence. That reasoning holds only while nothing has
     * *demonstrated* the scale is in doubt — and here the pair has. A declared basis says which
     * quantity the figure is measured per; it says nothing about where the figure's decimal point is.
     */
    @Test
    fun `a declared serving basis does not rescue a demonstrated ambiguity`() {
        val document = EighteenthSessionPairFixtures.crispsServing160532()

        val row = carbohydrateRowText(document)
        assertNotNull("precondition: the carbohydrate declaration must still be found", row)

        val offered = offeredAmounts(document)
        assertTrue("the bundle offered '38 g / 25 g', was $offered", offered.none { it == "38" })
        assertTrue("'15' must stay suppressed, was $offered", offered.none { it == "15" })
    }

    /**
     * The automatic path must not offer these figures either.
     *
     * Recovery is one of the two surfaces that shows a number; the proposal card is the other, and a
     * fix satisfied by moving a figure from one to the other is not a fix. This asks
     * [AutomaticScanAdvance.eligibility] — the same object recovery consults — so the two surfaces
     * are pinned to one answer.
     *
     * ## Note what is deliberately *not* asserted here
     *
     * `160532-812` parses **confidently** to `15 / PER_100_G`: its row reads
     * `koolhydraten, waarvan 15 g 38g`, so the candidate carries a unit and every structural rule
     * accepts it. That is correct and must stay so — a confident *parse* is a statement about
     * structure, and this repo has repeatedly recorded that conflating it with a statement about
     * digits is the error. The eligibility gate is where the scale question is answered, which is why
     * this asserts on the gate rather than on the reading.
     */
    @Test
    fun `the automatic path offers none of the three pairs`() {
        listOf(
            "160639-565" to EighteenthSessionPairFixtures.proteinBar160639(),
            "160501-961" to EighteenthSessionPairFixtures.crispsServing160501(),
            "160532-812" to EighteenthSessionPairFixtures.crispsServing160532(),
        ).forEach { (name, document) ->
            val report = NutritionTableInterpreter.interpret(document)
            val outcome = EvidenceResolver.resolve(
                listOf(
                    RecognitionEvidence(
                        source = EvidenceSource.FULL_FRAME_PASS_A,
                        report = report,
                        document = document,
                    ),
                ),
            )

            val verdict = AutomaticScanAdvance.eligibility(
                outcome = outcome,
                verification = AutomaticVerification.verify(document, report),
                document = document,
            )

            // Null means there was no confident reading to gate — also an acceptable outcome, and
            // what the two `NotFound` captures produce.
            if (verdict != null) {
                assertTrue(
                    "$name: a demonstrated pair ambiguity must withhold the figure, was $verdict",
                    verdict is ReadingEligibility.Verdict.Refused,
                )
            }
        }
    }
}
