package app.justthecarbs.ui.manual

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import app.justthecarbs.data.ProductRepository
import app.justthecarbs.domain.NutritionBasis
import app.justthecarbs.domain.NutritionValueValidator
import app.justthecarbs.domain.PortionConversion
import app.justthecarbs.domain.PortionParser
import app.justthecarbs.domain.PortionUnitKind
import app.justthecarbs.domain.Product
import app.justthecarbs.domain.ProductDataOrigin
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.UUID

enum class CarbsError { MALFORMED, OUT_OF_RANGE }

/**
 * A countable portion accepted from an OCR read, waiting for its product to exist (correction §2).
 *
 * `portion_units.productBarcode` is a foreign key to `products.barcode`, so this cannot be written
 * until the product is saved. Held as typed data rather than being persisted optimistically, which
 * is what let the scanner report "saved" for a row the database then rejected.
 */
data class PendingPortionUnit(
    val kind: PortionUnitKind,
    val conversion: PortionConversion,
)

data class ManualEntryUiState(
    val barcode: String = "",
    val name: String = "",
    val carbsPer100: String = "",
    /**
     * Null means genuinely unresolved, never "grams by default" (§5, startup-hardening pass).
     *
     * Reached when a scanned figure arrives with no basis the parser could establish — the label
     * printed a number with nothing to say what it was measured per. Defaulting to
     * [NutritionBasis.PER_100_G] here would silently pick a denominator the app never read, which
     * is exactly the "grams of what?" guess this app must never make on the user's behalf. Ordinary
     * manual entry (nothing carried in) still starts on grams — see [ManualEntryViewModel.start].
     */
    val basis: NutritionBasis? = NutritionBasis.PER_100_G,
    val packageAmount: String = "",
    val nameError: Boolean = false,
    val carbsError: CarbsError? = null,
    val savedBarcode: String? = null,
    /** Non-null when this entry will also create a countable portion (correction pass §2). */
    val pendingPortionUnit: PendingPortionUnit? = null,
    /**
     * The product saved but its portion did not.
     *
     * Surfaced rather than swallowed: the product genuinely exists and the user can carry on, but
     * they must not be told a portion was captured when it was not.
     */
    val portionSaveFailed: Boolean = false,
    /**
     * The product itself could not be written.
     *
     * Distinct from [portionSaveFailed], which reports a product that *was* saved without its
     * portion. Here nothing was stored, so there is nothing to carry on to — which is exactly why
     * it has to be said. Clearing `saving` alone re-enabled the button and changed nothing else on
     * screen, so a failed save was indistinguishable from a tap that never registered, and the
     * obvious response to that is to tap again and fail again.
     */
    val saveFailed: Boolean = false,
    /**
     * A save is in flight (release-freeze audit §8).
     *
     * The write is asynchronous and navigation only happens once it lands, so without this the Save
     * button stays enabled across the whole round trip. A second tap in that window starts a second
     * write, and because a portion unit is inserted with an autogenerated id, an OCR-carried
     * [PendingPortionUnit] would be persisted **twice** — two identical "1 slice" rows on one product.
     */
    val saving: Boolean = false,
) {
    val canSave: Boolean
        get() = !saving && name.isNotBlank() && basis != null && PortionParser.parse(carbsPer100) != null
}

/**
 * Manual entry (§27) and quick calculation (§28).
 *
 * Validation runs through the same [NutritionValueValidator] that guards remote data, so a typo
 * that produces an impossible value is caught wherever it came from.
 */
class ManualEntryViewModel(
    private val repository: ProductRepository,
) : ViewModel() {

    private val _state = MutableStateFlow(ManualEntryUiState())
    val state: StateFlow<ManualEntryUiState> = _state.asStateFlow()

    /**
     * Like [runCatching], but never catches [CancellationException] (P1 §14) — a plain
     * `runCatching` around a suspending repository write would report the coroutine's own
     * cancellation (e.g. this ViewModel cleared mid-save) as an ordinary failed save instead of
     * letting it propagate, which is exactly the structured-concurrency violation this exists to
     * avoid at every save call site below.
     */
    private suspend fun <T> runCatchingSuspend(block: suspend () -> T): Result<T> = try {
        Result.success(block())
    } catch (e: CancellationException) {
        throw e
    } catch (e: Exception) {
        Result.failure(e)
    }

    /**
     * Pre-fill from wherever the user came here from.
     *
     * The barcode arrives from an unknown scan, so any product created here becomes associated with
     * it and the next scan resolves locally (§26). [ocrCarbs] and [ocrBasis] arrive from a label
     * reading the user has already confirmed (§29) — they are a starting point, still editable,
     * never a value that has been accepted on the user's behalf.
     *
     * The basis defaults to grams only for ordinary entry — [ocrCarbs] blank, nothing carried in.
     * The moment a figure IS being carried in, a basis the parser could not resolve stays `null`
     * rather than silently becoming grams (§5, startup-hardening pass): [ocrCarbs] non-blank with
     * an unparsable [ocrBasis] is precisely the case a scanned reading with no established
     * denominator produces, and defaulting there would guess a unit the label never stated.
     */
    fun start(
        barcode: String?,
        ocrCarbs: String = "",
        ocrBasis: String = "",
        pendingPortionUnit: PendingPortionUnit? = null,
    ) {
        if (_state.value.name.isNotEmpty() || _state.value.carbsPer100.isNotEmpty()) return
        val parsedBasis = NutritionBasis.entries.firstOrNull { basis -> basis.name == ocrBasis }
        _state.update {
            it.copy(
                barcode = barcode.orEmpty(),
                carbsPer100 = ocrCarbs,
                basis = when {
                    parsedBasis != null -> parsedBasis
                    ocrCarbs.isBlank() -> it.basis
                    else -> null
                },
                pendingPortionUnit = pendingPortionUnit,
            )
        }
    }

    // Every edit clears [ManualEntryUiState.saveFailed]: the notice describes one attempt, and
    // leaving it standing would make the next successful save look like it had failed too.
    fun onNameChanged(value: String) =
        _state.update { it.copy(name = value, nameError = false, saveFailed = false) }

    fun onCarbsChanged(value: String) =
        _state.update { it.copy(carbsPer100 = value, carbsError = null, saveFailed = false) }

    fun onBasisChanged(basis: NutritionBasis) =
        _state.update { it.copy(basis = basis, saveFailed = false) }

    fun onPackageChanged(value: String) =
        _state.update { it.copy(packageAmount = value, saveFailed = false) }

    fun save() {
        val current = _state.value

        // Already writing. Set synchronously below, before any suspension point, so a second tap in
        // the same frame cannot slip past — `save()` is only ever called from the main thread.
        if (current.saving) return

        if (current.name.isBlank()) {
            _state.update { it.copy(nameError = true) }
            return
        }

        val carbs = PortionParser.parse(current.carbsPer100)
        if (carbs == null) {
            _state.update { it.copy(carbsError = CarbsError.MALFORMED) }
            return
        }
        // Guarded by canSave, which already requires a non-null basis — but save() must never
        // trust the button stayed disabled, since it is also the entry point for this ViewModel's
        // own tests. A null basis here means "the label never said what this figure is measured
        // per", and there is no value this app may write in its place.
        val basis = current.basis ?: return
        // The same ceiling remote data has to clear. A hand-typed 482 is a slipped decimal point,
        // and accepting it would produce a tenfold-wrong result with total confidence (§13).
        if (NutritionValueValidator.validateCarbsPer100(carbs.toDouble(), basis) == null) {
            _state.update { it.copy(carbsError = CarbsError.OUT_OF_RANGE) }
            return
        }

        // A product without a barcode still needs a stable key so it can live in Recents. The
        // synthetic id is namespaced so it can never collide with a real GTIN (§28).
        val key = current.barcode.ifBlank { "local:${UUID.randomUUID()}" }

        val product = Product(
            barcode = key,
            name = current.name.trim(),
            carbsPer100 = carbs,
            basis = basis,
            dataSource = ProductDataOrigin.MANUAL,
            packageAmount = PortionParser.parse(current.packageAmount),
        )
        val pending = current.pendingPortionUnit
        _state.update { it.copy(saving = true) }

        viewModelScope.launch {
            if (pending == null) {
                // A failed product write must not leave the button disabled forever: the screen would
                // be stuck with no way to retry and no explanation.
                runCatchingSuspend { repository.saveUserAuthoredProduct(product, origin = ProductDataOrigin.MANUAL) }
                    .onSuccess {
                        _state.update { it.copy(savedBarcode = key, saving = false, saveFailed = false) }
                    }
                    // Reported, not merely survived. The failure is cleared by the next edit or the
                    // next successful save, so it always describes the most recent attempt.
                    .onFailure { _state.update { it.copy(saving = false, saveFailed = true) } }
                return@launch
            }

            // Product first, portion second — the portion's foreign key needs the product row to
            // exist (correction pass §2). The two writes are made as two separate calls rather than
            // through `saveProductWithPortionUnit`, which performs exactly this pair in exactly this
            // order, precisely so **which one failed is known from where the failure happened**
            // instead of being inferred afterwards.
            //
            // The previous form wrapped both writes in one `runCatching` and then asked the store
            // whether a product row existed. That misclassifies whenever the barcode was already
            // known locally: a stale row from an earlier scan answers "yes" for a reason unrelated to
            // this save, so a failed *product* write was reported as a portion failure and the user
            // was sent to a calculator showing the old record. Nothing in the caught exception can
            // distinguish the two cases, so the ordering has to be visible here.
            val productSaved = runCatchingSuspend {
                repository.saveUserAuthoredProduct(product, origin = ProductDataOrigin.OCR)
            }
            if (productSaved.isFailure) {
                // Nothing was stored, so there is nothing to navigate to and no portion was
                // attempted — the ordering guarantees that, rather than a check asserting it.
                _state.update { it.copy(saving = false, saveFailed = true) }
                return@launch
            }

            // The OCR provenance is preserved: the portion was read off the package by the camera
            // even though the surrounding product was typed.
            val portionSaved = runCatchingSuspend {
                repository.saveUserPortionUnit(
                    barcode = key,
                    kind = pending.kind,
                    conversion = pending.conversion,
                    origin = ProductDataOrigin.OCR,
                )
            }
            // The product genuinely exists either way, so the user reaches the calculator either
            // way — but a portion that did not persist is reported rather than passed off as a
            // capture that happened. Unchanged behaviour; only how the case is identified moved.
            _state.update {
                it.copy(
                    savedBarcode = key,
                    portionSaveFailed = portionSaved.isFailure,
                    saving = false,
                    saveFailed = false,
                )
            }
        }
    }

    fun onNavigated() = _state.update { it.copy(savedBarcode = null) }
}
