package app.justthecarbs.ui.manual

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import app.justthecarbs.data.ProductRepository
import app.justthecarbs.domain.NutritionBasis
import app.justthecarbs.domain.NutritionValueValidator
import app.justthecarbs.domain.PortionConversion
import app.justthecarbs.domain.PortionParser
import app.justthecarbs.domain.PortionUnitKind
import app.justthecarbs.domain.Product
import app.justthecarbs.domain.ProductDataOrigin
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.UUID

enum class CarbsError { MALFORMED, OUT_OF_RANGE }

/**
 * A countable portion accepted from an OCR read, waiting for its product to exist (correction §2).
 *
 * `portion_units.productBarcode` is a foreign key to `products.barcode`, so this cannot be written
 * until the product is saved. Held as typed data rather than being persisted optimistically, which
 * is what let the scanner report "saved" for a row the database then rejected.
 */
data class PendingPortionUnit(
    val kind: PortionUnitKind,
    val conversion: PortionConversion,
)

data class ManualEntryUiState(
    val barcode: String = "",
    val name: String = "",
    val carbsPer100: String = "",
    val basis: NutritionBasis = NutritionBasis.PER_100_G,
    val packageAmount: String = "",
    val nameError: Boolean = false,
    val carbsError: CarbsError? = null,
    val savedBarcode: String? = null,
    /** Non-null when this entry will also create a countable portion (correction pass §2). */
    val pendingPortionUnit: PendingPortionUnit? = null,
    /**
     * The product saved but its portion did not.
     *
     * Surfaced rather than swallowed: the product genuinely exists and the user can carry on, but
     * they must not be told a portion was captured when it was not.
     */
    val portionSaveFailed: Boolean = false,
    /**
     * A save is in flight (release-freeze audit §8).
     *
     * The write is asynchronous and navigation only happens once it lands, so without this the Save
     * button stays enabled across the whole round trip. A second tap in that window starts a second
     * write, and because a portion unit is inserted with an autogenerated id, an OCR-carried
     * [PendingPortionUnit] would be persisted **twice** — two identical "1 slice" rows on one product.
     */
    val saving: Boolean = false,
) {
    val canSave: Boolean
        get() = !saving && name.isNotBlank() && PortionParser.parse(carbsPer100) != null
}

/**
 * Manual entry (§27) and quick calculation (§28).
 *
 * Validation runs through the same [NutritionValueValidator] that guards remote data, so a typo
 * that produces an impossible value is caught wherever it came from.
 */
class ManualEntryViewModel(
    private val repository: ProductRepository,
) : ViewModel() {

    private val _state = MutableStateFlow(ManualEntryUiState())
    val state: StateFlow<ManualEntryUiState> = _state.asStateFlow()

    /**
     * Pre-fill from wherever the user came here from.
     *
     * The barcode arrives from an unknown scan, so any product created here becomes associated with
     * it and the next scan resolves locally (§26). [ocrCarbs] and [ocrBasis] arrive from a label
     * reading the user has already confirmed (§29) — they are a starting point, still editable,
     * never a value that has been accepted on the user's behalf.
     */
    fun start(
        barcode: String?,
        ocrCarbs: String = "",
        ocrBasis: String = "",
        pendingPortionUnit: PendingPortionUnit? = null,
    ) {
        if (_state.value.name.isNotEmpty() || _state.value.carbsPer100.isNotEmpty()) return
        _state.update {
            it.copy(
                barcode = barcode.orEmpty(),
                carbsPer100 = ocrCarbs,
                basis = NutritionBasis.entries.firstOrNull { basis -> basis.name == ocrBasis }
                    ?: it.basis,
                pendingPortionUnit = pendingPortionUnit,
            )
        }
    }

    fun onNameChanged(value: String) =
        _state.update { it.copy(name = value, nameError = false) }

    fun onCarbsChanged(value: String) =
        _state.update { it.copy(carbsPer100 = value, carbsError = null) }

    fun onBasisChanged(basis: NutritionBasis) = _state.update { it.copy(basis = basis) }

    fun onPackageChanged(value: String) = _state.update { it.copy(packageAmount = value) }

    fun save() {
        val current = _state.value

        // Already writing. Set synchronously below, before any suspension point, so a second tap in
        // the same frame cannot slip past — `save()` is only ever called from the main thread.
        if (current.saving) return

        if (current.name.isBlank()) {
            _state.update { it.copy(nameError = true) }
            return
        }

        val carbs = PortionParser.parse(current.carbsPer100)
        if (carbs == null) {
            _state.update { it.copy(carbsError = CarbsError.MALFORMED) }
            return
        }
        // The same ceiling remote data has to clear. A hand-typed 482 is a slipped decimal point,
        // and accepting it would produce a tenfold-wrong result with total confidence (§13).
        if (NutritionValueValidator.validateCarbsPer100(carbs.toDouble(), current.basis) == null) {
            _state.update { it.copy(carbsError = CarbsError.OUT_OF_RANGE) }
            return
        }

        // A product without a barcode still needs a stable key so it can live in Recents. The
        // synthetic id is namespaced so it can never collide with a real GTIN (§28).
        val key = current.barcode.ifBlank { "local:${UUID.randomUUID()}" }

        val product = Product(
            barcode = key,
            name = current.name.trim(),
            carbsPer100 = carbs,
            basis = current.basis,
            dataSource = ProductDataOrigin.MANUAL,
            packageAmount = PortionParser.parse(current.packageAmount),
        )
        val pending = current.pendingPortionUnit
        _state.update { it.copy(saving = true) }

        viewModelScope.launch {
            if (pending == null) {
                // A failed product write must not leave the button disabled forever: the screen would
                // be stuck with no way to retry and no explanation.
                runCatching { repository.saveUserAuthoredProduct(product, origin = ProductDataOrigin.MANUAL) }
                    .onSuccess { _state.update { it.copy(savedBarcode = key, saving = false) } }
                    .onFailure { _state.update { it.copy(saving = false) } }
                return@launch
            }

            // Product first, portion second, through the repository's one ordered boundary — the
            // portion's foreign key needs the product row to exist (correction pass §2). The OCR
            // provenance is preserved: the portion was read off the package by the camera even
            // though the surrounding product was typed.
            val saved = runCatching {
                repository.saveProductWithPortionUnit(
                    product = product,
                    kind = pending.kind,
                    conversion = pending.conversion,
                    origin = ProductDataOrigin.OCR,
                )
            }

            saved.onFailure {
                // The product may still have landed — the portion is the write that can fail on its
                // own. Report the portion honestly instead of claiming a capture that did not
                // happen; the user reaches the calculator either way and can add it by hand.
                _state.update { it.copy(savedBarcode = key, portionSaveFailed = true, saving = false) }
            }
            saved.onSuccess {
                _state.update { it.copy(savedBarcode = key, portionSaveFailed = false, saving = false) }
            }
        }
    }

    fun onNavigated() = _state.update { it.copy(savedBarcode = null) }
}
